version: "3.9"
services:
  app:
    build:
      dockerfile: ./Dockerfile
    command: [ "main.go" ]
    depends_on: [ "bigquery" ]
  bigquery:
    image: ghcr.io/goccy/bigquery-emulator:0.1.26
    command: [ "--project", "test-project", "--log-level", "debug" ]
